services:
  - type: web
    name: candidate-search-app
    env: node
    buildCommand: "npm run build"
    startCommand: "serve -s dist -l 3000"
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: DISABLE_BUN
        value: true
    routes:
      - type: rewrite
        source: "/(.*)"
        destination: "/index.html"
