services:
  - type: web
    name: candidate-search-app
    env: node
    buildCommand: "npm run build"
    startCommand: "serve -s dist -l $PORT"
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
